### ISSUE TITLE
Recreate test resources in dev environment

### ISSUE THREAD

**Issue by justinlittman** [LD4P/rdf2marc#107]
Blocked by https://github.com/LD4P/sinopia/issues/325

The development environment currently hosts a trio of resources used for testing:
* Admin md: https://api.development.sinopia.io/resource/4ccf09fb-62e9-4f80-8a04-259fd7d68caa
* Work: https://api.development.sinopia.io/resource/f629614c-7ae7-49c1-acc8-4488d6dc5f37
* Instance: https://api.development.sinopia.io/resource/4bf07817-38a4-41d5-8498-8a9a36b88ec4

As reported in #104, the test BF:instance is no longer compatible with rdf2marc and is based on the legacy `ld4p:RT:bf2:*` templates.

The goal of this ticket is to recreate these test resources in dev using the newer `pcc:bf2:*` templates.

To accomplish this, the `pcc:bf2:*` templates need to be copied from stage to development.

- [x] Create a new group called "admin" in development Cognito and add Sinopia developers.
- [x] Change [permissions](https://github.com/LD4P/sinopia_api/blob/main/src/permissions.js) in Sinopia API so that members of the "admin" group pass permissions checks. See https://github.com/LD4P/sinopia_api/issues/193
- [x] Add overwrite option to `resource copy` in Sinopia CLI that will check if a resource exists and if it already exists, uses a `put` instead of a `post`.
- [x] Use Sinopia CLI `resource list` and grep to get a list of resource templates in stage that start with `ld4p:RT:bf2:`.
- [x] Use Sinopia CLI `resource copy` with overwrite option to copy the resource templates from stage to development.
- [x] In Sinopia development, manually recreate the test resources.
- [x] Test with `rdf2marc`.
- [ ] Update `rdf2marc` README with the new resources.

**Comment by NancyL** [comment]
As a note, the ld4p templates are not legacy templates, but we certainly should be doing testing using the pcc templates.

**Comment by mjgiarlo** [comment]
@justinlittman https://github.com/LD4P/sinopia_cli/pull/1/ addresses the sinopia CLI changes needed. 

I'm having less success with the "In Sinopia development, manually recreate the test resources" step because it's not clear to me which RT(s) I should be using to base resource changes on. For instance, I'm looking at this dev resource: https://api.development.sinopia.io/resource/4ccf09fb-62e9-4f80-8a04-259fd7d68caa It appears to be based on the `ld4p:RT:bf2:AdminMetadata:BFDB` template (presumably a legacy one). What's not clear to me is which `pcc:bf2:` template maps to this one. Trying to find similar ones... here's what I see in stage and dev:

* `pcc:bf2:AdminMetadata`
* `pcc:bf2:AdminMetadata:GenerationProcess`
* `pcc:bf2:AdminMetadata:Status`
* `Stanford:pcc:bf2:AdminMetadata`

Current state: two of the three existing dev resources (`f629614c-7ae7-49c1-acc8-4488d6dc5f37` & `4ccf09fb-62e9-4f80-8a04-259fd7d68caa`) fail when run through rdf2marc break with `'Work (bf:instanceOf) not specified for Instance'`. The third dev resource (`4bf07817-38a4-41d5-8498-8a9a36b88ec4`) produces MARC output and no errors are raised.

I could use some advice about what else to do to finish this issue. Thanks!

**Comment by mjgiarlo** [comment]
New instance in dev: fae34165-c69a-4caa-9b9a-2448f71cc340

**Comment by mjgiarlo** [comment]
Blocked by https://github.com/LD4P/sinopia/issues/325

**Comment by justinlittman** [comment]
@mjgiarlo Can you just skip the status property for now?

**Comment by mjgiarlo** [comment]
@justinlittman As in... leave the status mapping alone, and when it raises due to having a BF URI, eat it and continue, leaving the status mapping blank? Sure, that'd easy enough.

**Comment by justinlittman** [comment]
No, in the admin metadata resource don't provide a value for the status (i.e., leave it blank).

**Comment by mjgiarlo** [comment]
@justinlittman Sure, I can edit that data out in dev, no problem.

Here's the current rdf2marc diff, btw:

```diff
26,27c26,27
< 264  1 $a Virginia $b  $c 202X 
< 264  1 $a Utah $b  $c 2020 
---
> 264  1 $a Virginia $c 202X 
> 264  1 $a Utah $c 2020 
51c51
< 758    $4 http://id.loc.gov/ontologies/bibframe/instanceOf $i Instance of: $a preferred title for work $0 https://api.development.sinopia.io/resource/f629614c-7ae7-49c1-acc8-4488d6dc5f37 
---
> 758    $4 http://id.loc.gov/ontologies/bibframe/instanceOf $i Instance of: $a preferred title for work $0 https://api.development.sinopia.io/resource/b7f5739b-1f8c-4155-968e-4aa463bac607 
53c53
< 884    $a Sinopia rdf2marc $g 20211111 $k https://api.development.sinopia.io/resource/4bf07817-38a4-41d5-8498-8a9a36b88ec4 $u https://github.com/LD4P/rdf2marc 
---
> 884    $a Sinopia rdf2marc $g 20211115 $k https://api.development.sinopia.io/resource/83fe8c98-e34b-42aa-b6d3-07cc11c3faa6 $u https://github.com/LD4P/rdf2marc 
```

**Comment by mjgiarlo** [comment]
@justinlittman I don't see anything about dev in the rdf2marc README, the last step in this issue, so I guessed that this was the change we wanted: https://github.com/LD4P/rdf2marc/pull/144

**Comment by NancyL** [comment]
I'm not sure what would happen with the MARC going to OCLC (or even to Symphony?) with it blank. The default is "n" for all other systems. @vitustang would you know?

**Comment by mjgiarlo** [comment]
Hi, @NancyL. I believe it's still defaulting to `n`: 

```
LEADER      nai a22     5u 4500
```
