### ISSUE TITLE
Reconsider admin metadata status code mapping?

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/rdf2marc#141]
In working through https://github.com/LD4P/rdf2marc/issues/107, I've gotten as far as creating new admin metadata, work, and instance resources in dev based on `pcc:bf2:*` templates rather than `ld4p:RT:bf2:*` templates. The rdf-to-marc mapping tool (`rdf2marc`) fails on the instance*, apparently because the status property in admin metadata was changed from expecting a string code (`n`) to expecting a URI code (`http://id.loc.gov/vocabulary/mstatus/n`).

Is this change intended? If so, I think this may mean `rdf2marc` needs its model mapping changed. How should we map these URIs (the ones in the Scheme Members list in https://id.loc.gov/vocabulary/mstatus.html) to these valid MARC leader status code strings? 

* Note that there may in fact be other failures looming behind this one, but we'll get there soon enough once this issue is resolved.

**Comment by NancyL** [comment]
So I don't think this is really the issue, since it works fine in stage--see https://api.stage.sinopia.io/resource/b8843818-7961-4da6-bc92-401a9f75b8f6  and its associated instance, which converts just fine to MARC. 

In rdf2marc these would go in the leader 05--Record status and it would need to be the code, not the URI. However, LC has expanded the codes beyond 05, so not sure how well those others would work once they get in OCLC. They do specify a default of "n" in conversion. 

But we aren't currently using those codes, and I'm not that sure anyone is in Sinopia. So if you just want to ignore it and fill in the "n" for now that's fine with me

**Comment by mjgiarlo** [comment]
@justinlittman @NancyL I believe this is indeed already an issue in stage for resources that have admin metadata using the status URI. E.g.:

```
$ exe/rdf2marc https://api.stage.sinopia.io/resource/133d4c19-9549-45bb-b899-013a4da5a7d3
Traceback (most recent call last):
        6: from exe/rdf2marc:16:in `<main>'
        5: from /home/mjg/workspace/rdf2marc/lib/rdf2marc/converter.rb:13:in `convert'
        4: from /home/mjg/workspace/rdf2marc/lib/rdf2marc/rdf2model.rb:8:in `to_model'
        3: from /home/mjg/workspace/rdf2marc/lib/rdf2marc/rdf2model/mapper.rb:12:in `generate'
        2: from /home/mjg/workspace/rdf2marc/lib/rdf2marc/rdf2model/mappers/leader.rb:10:in `generate'
        1: from /home/mjg/workspace/rdf2marc/lib/rdf2marc/graph_query.rb:23:in `path_first_literal'
/home/mjg/workspace/rdf2marc/lib/rdf2marc/graph_query.rb:82:in `to_literal': Not a literal: http://id.loc.gov/vocabulary/mstatus/n (Rdf2marc::MappingError)
```

**Comment by mjgiarlo** [comment]
@justinlittman @NancyL for now, I'll put in a little PR that traps for this condition and default to `n` for the mapping. thanks!
