### ISSUE TITLE
SPIKE: Investigate alternative to AWS Lambda for hosting

### ISSUE THREAD

**Issue by jermnelson** [LD4P/rdf2marc#4]
The current hosting for `rdf2marc` is using an AWS Lambda that has a timeout period that will cease execution even if rdf2marc is still processing  a request. This 1/2 day spike is to determine:

1. Would hosting as a Fargate task be a better alternative?
1. How hard would it be to refactor as a Fargate task?
1. Are there other options for hosting we should consider?

**Comment by justinlittman** [comment]
Just to be clear, the issue is not the lambda timing out -- the timeout can be increased to a suitable length; it is the API Gateway, which can't be increased.

Two possible approaches:
1. Sinopia Editor sends a request for a MARC record to Sinopia API. Sinopia API initiates the lambda. Lambda performs the transform and writes the result to a file in an S3 bucket. Sinopia Editor polls the S3 bucket until the file becomes available.
2. Sinopia Editor sends a request to a Rails app running as a Fargate service. The Rails app provides the Sinopia Editor with a job id and kicks off an ActiveJob that performs the transform. Sinopia Editor polls the Rails app based on the job id. (This is the same model that SDR API uses.)

Advantages of this first approach:
* Simple (in that it relies on AWS infrastructure).
* Less Ruby code in an otherwise JS project.
* Auto-scaling

Advantages of the second approach:
* Follows an existing model that we've used elsewhere.
* Easier to run in a local development environment.

**Comment by justinlittman** [comment]
Another option to consider: https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js

**Comment by jimfhahn** [comment]
per the investigations on a hosting option: I was looking for something to get up and running quickly to try out the web-option, as I do not have access to AWS, this was the result in [glitch](https://glitch.com/): https://glitch.com/~rdf2marc
https://rdf2marc.glitch.me/lambda-api/demo.html

**Comment by justinlittman** [comment]
Nice @jimfhahn!

**Comment by jermnelson** [comment]
Moving this back to backlog.
